name: workflow Events
on:
  pull_request:
    branches: 
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write   
    steps:
    - name: Adicionado Funcionalidade
      run: echo "Teste de action"
    - name: Action de teste
      uses: actions/github-script@v6
      with: 
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Adicionando um comentário no meu PR'
          }) 
